services:
    app:
        build:
            args:
                user: appuser
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: medical-app
        container_name: medical-app-container
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - medical-network

    db:
        image: mysql:8.0
        container_name: medical-db-container
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - medical-network

    nginx:
        image: nginx:alpine
        container_name: medical-nginx-container  # Changed container_name here
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - medical-network

networks:
    medical-network:
        driver: bridge
